language: python
python:
  - "3.7"
install:
  - pip install -r ./scripts/requirements.txt
matrix:
  include:
    - name: Test Docker based on Ubuntu 18.04 LTS 
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh start.sh --test
    - name: Test Docker based on Ubuntu 19.04 LTS
      os: linux
      dist: trusty
      sudo: required
      services: docker
      script:
        - sh start.sh --test